# Generated by Django 2.2.7 on 2019-11-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='subdistrict_name',
        ),
    ]
