# Generated by Django 2.2.7 on 2019-11-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_aldeia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aldeia',
            name='descriptio_name',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='aldeia',
            name='id_aldeia_name',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='aldeia',
            name='name',
            field=models.CharField(max_length=325),
        ),
    ]
