# Generated by Django 2.2.8 on 2020-02-08 06:46

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_subdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istoriaviazen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('upload_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istoria', to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(related_name='subistoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
