# Generated by Django 2.2.8 on 2020-02-15 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_phototimor_point'),
        ('map', '0004_istoriaviazen'),
    ]

    operations = [
    ]
