# Generated by Django 2.2.7 on 2020-03-31 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_merge_20200215_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 5, 55, 28, 265048, tzinfo=utc)),
        ),
    ]
