# Generated by Django 2.2.7 on 2020-01-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200116_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTimor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Timor Photo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='point',
            options={},
        ),
    ]
