# Generated by Django 2.2.7 on 2020-04-02 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200331_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='istoriaviazen',
            name='image_trip',
            field=models.ImageField(default='', upload_to='photos', verbose_name='Timor Photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 1, 24, 8, 868979, tzinfo=utc)),
        ),
    ]
