# Generated by Django 2.2.10 on 2020-04-04 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200402_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoriaviazen',
            name='people',
        ),
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 2, 26, 5, 364580, tzinfo=utc)),
        ),
    ]
