# Generated by Django 2.2.10 on 2020-06-11 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200404_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.RenameField(
            model_name='istoriaviazen',
            old_name='date',
            new_name='duration_of_trip',
        ),
        migrations.RemoveField(
            model_name='istoriaviazen',
            name='image_trip',
        ),
        migrations.RemoveField(
            model_name='istoriaviazen',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='istoriaviazen',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='istoriaviazen',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phototimor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phototimor',
            name='istoriaviazen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='map.IstoriaViazen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototimor',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
