# Generated by Django 2.2.10 on 2020-06-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200611_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototimor',
            name='istoriaviazen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='map.IstoriaViazen'),
        ),
    ]
