# Generated by Django 2.2.7 on 2020-04-05 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200404_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoriaviazen',
            name='image_trip',
        ),
        migrations.AlterField(
            model_name='istoriaviazen',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='istoria', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 9, 34, 32, 866993, tzinfo=utc)),
        ),
    ]
