# Generated by Django 2.2.10 on 2020-04-25 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20200412_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 2, 10, 31, 871188, tzinfo=utc)),
        ),
    ]
