# Generated by Django 2.2.7 on 2020-04-14 02:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0010_auto_20200412_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoriaviazen',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='istoriaviazen',
            name='aldeia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='aldeialocation', to='map.Aldeia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='istoriaviazen',
            name='date_sumbited',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 2, 33, 5, 728464, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='istoriaviazen',
            name='modified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='istoriaviazen',
            name='people',
            field=models.ManyToManyField(related_name='usersistoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phototimor',
            name='modified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='phototimor',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 2, 33, 5, 731510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='istoriaviazen',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useristoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phototimor',
            name='istoriaviazen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istoriaviazen', to='map.IstoriaViazen'),
        ),
    ]
