# Generated by Django 2.2.7 on 2020-04-05 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20200405_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoriaviazen',
            name='image_trip',
        ),
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 10, 1, 18, 109247, tzinfo=utc)),
        ),
    ]
