# Generated by Django 2.2.10 on 2020-04-25 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20200425_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istoriaviazen',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
