# Generated by Django 2.2.10 on 2020-04-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20200425_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
