# Generated by Django 2.2.7 on 2020-05-08 12:45

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_delete_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istoriaviazen',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
