# Generated by Django 3.2 on 2021-11-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20200613_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototimor',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnail', verbose_name='Timor Photo thumbnail'),
        ),
    ]
