# Generated by Django 3.2 on 2022-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototimor',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnail', verbose_name='Timor Photo thumbnail'),
        ),
    ]
